on:
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    - name: Install dependencies
      run: 'cd scrapegraph-py

        uv sync --frozen

        '
    - name: Analysing the code with pylint
      run: 'cd scrapegraph-py

        uv run poe pylint-ci

        '
    - name: Check Pylint score
      run: "cd scrapegraph-py\npylint_score=$(uv run poe pylint-score-ci | grep 'Raw\
        \ metrics' | awk '{print $4}')\nif (( $(echo \"$pylint_score < 8\" | bc -l)\
        \ )); then\n  echo \"Pylint score is below 8. Blocking commit.\"\n  exit 1\n\
        else\n  echo \"Pylint score is acceptable.\"\nfi\n"
